project:
  type: website
  output-dir: docs

website:
  title: "Cátedra de Estructural — UTN FRLP"
  page-footer:
    center: "Ing. Ronconi / Ing. Zangara / Ing. Vaello · UTN Facultad Regional La Plata · 2026"

format:
  html:
    theme: cosmo
    lang: es